services:
  - type: web
    name: tnt-insight-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    autoDeployTrigger: commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
